name: Deploy

on:
  workflow_dispatch:

env:
  TAG_BASE: ghcr.io/${{ github.repository }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.1.0
        with:
          token: ${{ github.token }}
          version: '2.1.0'

      - name: Push manifests
        run: |
          flux push artifact oci://$TAG_BASE/manifests:test \
            --path="kube" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git tag --points-at HEAD)/$(git rev-parse HEAD)"